### ISSUE TITLE
Function list in C++ does not detect functions with parameter comments containing parantheses (reopen of #4899) #5522

### ISSUE THREAD

**Issue by Firecharmlily** [Firecharmlily/Summerplusplus#2]
### **Description of the Issue**
Function list in C++ does not detect functions with parameter comments containing parantheses

### **Steps to Reproduce the Issue**
Add this code in a .cpp file. "Working" is detected by the function list but "NotWorking" is not, until you remove the ( in the comment. This style of documentation is common I think...

```
void Working(
int a // SomeText
)
{
}

void NotWorking(
int a // SomeText(
)
{
}
```
### **Expected Behavior**
Both should display.

### **Actual Behavior**
Some functions are not displayed.

### **Debug Information**
V7.6.6 Win32

![image](https://user-images.githubusercontent.com/22859877/68309104-f20ae880-007b-11ea-9e7f-7f90154c689a.png)

**Comment by Firecharmlily** [comment]
Have narrowed down the problem being related to the xml tree or parserfunction

**Comment by Nandith-Narayan** [comment]
Did you get the function list working? 
I'm trying to use the xml file from the notepad++ git

**Comment by Firecharmlily** [comment]
no but so far i know this link may help us understand it: https://stackoverflow.com/questions/48410830/extract-function-name-from-notepad-for-functionlist

**Comment by Firecharmlily** [comment]
Line 256 is where the problem possibly is.

```
<functionName>
                        <nameExpr expr="(?x)                                    # Utilize inline comments (see `RegEx - Pattern Modifiers`)
                                [A-Za-z_\x7F-\xFF][\w\x7F-\xFF]*
                                \s*\(                                           # start of parameters
                                (?s:.*?)                                        # whatever, until...
                                \)                                              # end   of parameters
                            " />
                        <!-- comment out the following node to display the method with its parameters -->
<!--                        <nameExpr expr="[A-Za-z_\x7F-\xFF][\w\x7F-\xFF]*" /> -->
                    </functionName>

```

**Comment by Firecharmlily** [comment]
Has been fixed!!! :D
