### ISSUE TITLE
Feature request: Add "Save As" button between "Save" and "Save All" buttons. Thanks. #5056

### ISSUE THREAD

**Issue by Firecharmlily** [Firecharmlily/Summerplusplus#5]
Feature request: Add "Save As" button between "Save" and "Save All" buttons. Thanks.

**Comment by Firecharmlily** [comment]
have created save as button icon

**Comment by Nandith-Narayan** [comment]
Woot

**Comment by Firecharmlily** [comment]
Added custom save as button, it works, and is completely functional
